### ISSUE TITLE
有些歌解的时候报头错误，我也不知道转成功没

### ISSUE THREAD

**Issue by oschanger** [nondanee/ncmdump#15]
Traceback (most recent call last):
  File "ncmdump.py", line 138, in <module>
    dump(path)
  File "ncmdump.py", line 29, in dump
    assert binascii.b2a_hex(header) == b'4354454e4644414d'
AssertionError

**Comment by nondanee** [comment]
没成功，难道 magic number 也改了？
解决了？秒 close 啊……
